TRADE_STATUS_FLOW = {
    "INITIATED": ["SELLER_CONFIRMED", "REJECTED"],
    "SELLER_CONFIRMED": ["DOCUMENTS_UPLOADED"],
    "DOCUMENTS_UPLOADED": ["BANK_REVIEWING"],
    "BANK_REVIEWING": ["PAYMENT_RELEASED", "DISPUTED"],  # ✅ ADD
    "PAYMENT_RELEASED": ["COMPLETED"],
    "REJECTED": [],
    "DISPUTED": []  # terminal (or later escalation)
}
